name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5

      - name: 'Go Set up'
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: 'Install golangci-lint'
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

      - name: 'Go Lint'
        run: golangci-lint run

      - name: 'Go Build'
        run: go build -v ./

  build-image:
    runs-on: ubuntu-latest
    needs: lint
    outputs:
      version: ${{ env.version }}
    steps:
      - uses: actions/checkout@v5

      - name: 'Extract version'
        run: |
          echo "version=$(git describe --tags --dirty --always --abbrev=12)" >> "$GITHUB_ENV"

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'Build'
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            VERSION=${{ env.version }}
          push: false
          load: true
          tags: rootfsimage
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 'Export rootfs'
        run: |
          id=$(docker create rootfsimage true)
          mkdir -p ./plugin/rootfs/
          docker save rootfsimage -o plugin/plugin-rootfs.tar
          docker rm -vf "$id"

      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: plugin-rootfs
          path: plugin/
          retention-days: 1
          if-no-files-found: error