name: Publish

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_run:
    workflows: [ "Build" ]
    branches: [ main ]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v5

      - name: 'Download artifact'
        uses: actions/download-artifact@v5
        with:
          name: plugin-rootfs
          path: plugin/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}


      - name: 'Log into registry'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: 'Publish latest'
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker plugin create "docker.io/${{ secrets.DOCKER_USERNAME }}/op-connect-secret-driver" ${PWD}/plugin
          docker plugin push "docker.io/${{ secrets.DOCKER_USERNAME }}/op-connect-secret-driver"

      - name: 'Publish tagged'
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          docker plugin rm "docker.io/${{ secrets.DOCKER_USERNAME }}/op-connect-secret-driver" || true
          docker plugin create "docker.io/${{ secrets.DOCKER_USERNAME }}/op-connect-secret-driver:${{ github.ref_name }}" ${PWD}/plugin
          docker plugin push "docker.io/${{ secrets.DOCKER_USERNAME }}/op-connect-secret-driver:${{ github.ref_name }}"